'use strict';
const $=id=>document.getElementById(id), enc=new TextEncoder(),dec=new TextDecoder();
const un64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const b64=b=>{let s='';for(const x of new Uint8Array(b))s+=String.fromCharCode(x);return btoa(s)};
let data,key,decisions={},limit=20,queue=Promise.resolve();
const storageKey='chuck-video-review-decisions-v1';
const labels={pending:'미검토',approve:'승인',revise:'수정',hold:'보류'};
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
function status(s){$('status').textContent=s}
async function seal(value){const iv=crypto.getRandomValues(new Uint8Array(12));return {iv:b64(iv),ciphertext:b64(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(value))))}}
async function open(p){return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(p.iv)},key,un64(p.ciphertext))))}
function persist(){const snapshot=JSON.parse(JSON.stringify(decisions));status('저장 중…');queue=queue.catch(()=>{}).then(async()=>{localStorage.setItem(storageKey,JSON.stringify(await seal({version:data.version,decisions:snapshot})));status('이 브라우저에 저장됨 · 서버 전송 없음')}).catch(()=>{status('저장 실패! 브라우저 저장 공간/권한 확인 후 JSON을 내보내세요.');throw Error('local save failed')});queue.catch(()=>{});return queue}
$('unlock').onsubmit=async e=>{e.preventDefault();$('gateMsg').textContent='암호화 자료 여는 중…';try{const p=await(await fetch('payload.json')).json();const material=await crypto.subtle.importKey('raw',enc.encode($('password').value),'PBKDF2',false,['deriveKey']);key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:un64(p.salt),iterations:p.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);data=await open(p);decisions={};let warning='';try{const saved=localStorage.getItem(storageKey);if(saved){const d=await open(JSON.parse(saved));if(d.version!==data.version)throw Error();decisions=validate(d.decisions)}}catch{warning='기존 저장을 읽지 못했습니다. 덮어쓰기 전 이전 JSON 백업을 확인하세요.'} $('password').value='';$('gate').hidden=true;$('app').hidden=false;const c=data.counts;$('scope').textContent=`게시본 ${c.posts}개 · 편집 후보 ${c.candidates}개 · 표본 대조 ${c.reviewed}개 · Drive 경로 ${c.inventory}개`;status(warning||'검수 준비 완료 · 로컬 저장');render()}catch{key=null;data=null;$('gateMsg').textContent='코드가 다르거나 자료를 읽지 못했습니다.'}};
function validate(ds){if(!ds||typeof ds!=='object'||Array.isArray(ds))throw Error('invalid');const ids=new Set(data.records.map(r=>r.id));const out={};for(const [id,v]of Object.entries(ds)){if(!ids.has(id)||!v||typeof v!=='object')throw Error('unknown record');const o={};for(const f of ['title','credit','channel','playlist','notes','state','updatedAt']){if(v[f]!==undefined){if(typeof v[f]!=='string'||v[f].length>10000)throw Error('invalid field');o[f]=v[f]}}if(o.state&&!Object.hasOwn(labels,o.state))throw Error('invalid state');out[id]=o}return out}
function change(id,field,value){decisions[id]={...(decisions[id]||{}),[field]:value,updatedAt:new Date().toISOString()};persist()}
function field(card,label,id,f,value){const l=node('label',label);const input=node(f==='notes'?'textarea':'input');input.value=value||'';input.dataset.field=f;input.maxLength=10000;input.addEventListener('input',()=>change(id,f,input.value));l.append(input);card.append(l)}
function detail(dl,label,value){dl.append(node('dt',label),node('dd',value||'미확인'))}
function render(){const q=$('search').value.toLowerCase().trim(),view=$('view').value,filter=$('filter').value;const arr=(view==='inventory'?data.inventory:data.records.filter(r=>r.kind===view)).filter(r=>JSON.stringify(r).toLowerCase().includes(q)&&(view==='inventory'||filter==='all'||(decisions[r.id]?.state||'pending')===filter));$('count').textContent=`${arr.length}개 · ${Math.min(limit,arr.length)}개 표시`;const root=$('cards');root.replaceChildren();for(const r of arr.slice(0,limit)){const card=node('article');if(view==='inventory'){card.append(node('h2',r.path.split('/').pop()));const dl=node('dl');detail(dl,'Drive 경로 (파일 링크 미확보)',r.path);detail(dl,'분류',r.category);detail(dl,'폴더',r.group);detail(dl,'파일 크기 bytes',r.bytes);detail(dl,'수정일 (게시일 아님)',r.mtime_local);card.append(dl);root.append(card);continue}const d=decisions[r.id]||{};card.dataset.id=r.id;card.append(node('span',labels[d.state||'pending'],'tag'),node('h2',r.title));const dl=node('dl');detail(dl,'Instagram 원 게시 / 계정',r.account);if(r.instagram){const a=node('a','Instagram 게시물 열기 ↗');a.href=r.instagram;a.target='_blank';a.rel='noopener noreferrer';dl.append(a)}detail(dl,r.dateLabel||'게시일 (추출 메타데이터)',r.date);detail(dl,'원본 확실성',r.certainty);detail(dl,'사본 / 후보 유형',r.copy);detail(dl,'Drive 원본 후보 경로',r.path);if(r.postedPath)detail(dl,'Instagram 압축 사본 경로',r.postedPath);detail(dl,'협업 / 중복',r.collab);if(r.observation)detail(dl,'기존 대조 메모',r.observation);card.append(dl);if(r.image&&data.images[r.image]){const det=node('details');det.append(node('summary','기존 표본 이미지 보기 · 확대 가능'));det.addEventListener('toggle',()=>{if(det.open&&!det.querySelector('img')){const img=node('img');img.src=data.images[r.image];img.alt='9월 13일 대조 표본 — 후보 ID와 파일명 확인';det.append(img)} });card.append(det)}field(card,'YouTube 제목',r.id,'title',d.title??r.title);field(card,'대상 채널 (제안/미확인 · 아직 생성하지 않음)',r.id,'channel',d.channel);field(card,'재생목록 (미확인)',r.id,'playlist',d.playlist);field(card,'크레딧 / 음원 권리 (미확인)',r.id,'credit',d.credit);field(card,'검수 메모 · 원본 파일 / 다른 버전 / 모르겠음',r.id,'notes',d.notes);const actions=node('div',undefined,'actions');for(const [s,t]of Object.entries(labels)){const b=node('button',t);b.setAttribute('aria-pressed',String((d.state||'pending')===s));b.onclick=()=>{change(r.id,'state',s);render()};actions.append(b)}card.append(actions);root.append(card)}$('more').hidden=limit>=arr.length}
for(const id of ['view','filter','search'])$(id).addEventListener(id==='search'?'input':'change',()=>{limit=20;render()});$('more').onclick=()=>{limit+=20;render()};
$('export').onclick=async()=>{await queue.catch(()=>{});const value={schema:'chuck-video-review/1',version:data.version,exportedAt:new Date().toISOString(),storage:'device-local; no server sync',decisions};const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const a=node('a');a.href=URL.createObjectURL(blob);a.download='CHUCK-video-review-decisions.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);status('JSON 다운로드 요청됨 · 다운로드 파일을 Telegram으로 직접 보내주세요 (평문)')};
$('import').onchange=async()=>{try{const f=$('import').files[0];if(!f)return;if(f.size>5000000)throw Error();const x=JSON.parse(await f.text());if(x.schema!=='chuck-video-review/1'||x.version!==data.version)throw Error();const incoming=validate(x.decisions);if(!confirm(`${Object.keys(incoming).length}개 결정을 가져올까요? 같은 항목의 현재 결정을 덮어씁니다.`))return;decisions={...decisions,...incoming};await persist();render();status('가져오기 완료 · 이 브라우저에 암호화 저장됨')}catch{status('가져오기 실패 · 형식/버전/항목 ID 또는 저장 공간 확인')}finally{$('import').value=''}};
$('lock').onclick=async()=>{await queue.catch(()=>{});location.reload()};window.addEventListener('beforeunload',()=>{});
